/**
 * @fileoverview Extended HAR Types definitions for Waterfall Tools
 * Uses JSDoc syntax to provide type safety in IDEs for plain Vanilla JS natively.
 */

/**
 * @typedef {Object} Creator
 * @property {string} name - Name of the creator tool (e.g., waterfall-tools)
 * @property {string} version - Version of the tool
 */

/**
 * @typedef {Object} ExtendedHAREntry
 * @property {string} startedDateTime
 * @property {number} time
 * @property {Object} request
 * @property {Object|ExtendedHARResponse} response
 * @property {Object} cache
 * @property {Object|ExtendedHARTimings} timings
 * @property {string} [serverIPAddress]
 * @property {string} [connection]
 * @property {string} [pageref]
 * 
 * -- Waterfall Tools Extended Request Dictionaries --
 * @property {Object[]} [_chunks]
 * @property {Object} [_headers]
 * @property {Object} [_dns_info]
 * @property {Object} [_dns_details]
 * @property {Object} [_cpuTimes]
 * @property {Object} [_js_timing]
 * @property {Object} [_certificates]
 * @property {Object} [_font_details]
 * @property {Object} [_image_details]
 * @property {Object} [_securityDetails]
 * @property {Object} [_tls_cipher_suite]
 * 
 * -- Waterfall Tools Extended Request Scalars --
 * @property {string} [_id]
 * @property {string} [_request_id]
 * @property {string} [_raw_id]
 * @property {string} [_frame_id]
 * @property {string} [_netlog_id]
 * @property {string} [_body_id]
 * @property {string} [_body_file]
 * @property {string} [_body_hash]
 * @property {string} [_body_url]
 * @property {string} [_full_url]
 * @property {string} [_url]
 * @property {string} [_documentURL]
 * @property {string} [_host]
 * @property {string} [_ip_addr]
 * @property {string} [_protocol]
 * @property {string} [_method]
 * @property {string} [_request_type]
 * @property {string} [_type]
 * @property {string} [_contentType]
 * @property {string} [_contentEncoding]
 * @property {string} [_cacheControl]
 * @property {string} [_expires]
 * @property {string} [_priority]
 * @property {string} [_initial_priority]
 * @property {string} [_initiator]
 * @property {string} [_initiator_type]
 * @property {string} [_cdn_provider]
 * @property {number} [_index]
 * @property {number} [_number]
 * @property {number|boolean} [_is_secure]
 * @property {boolean} [_isSameSite]
 * @property {boolean} [_is_base_page]
 * @property {boolean} [_final_base_page]
 * @property {number} [_responseCode]
 * @property {number|string} [_socket]
 * @property {number|string} [_initiator_line]
 * @property {number|string} [_initiator_column]
 * @property {number} [_bytesIn]
 * @property {number} [_bytesOut]
 * @property {number} [_objectSize]
 * @property {number} [_objectSizeUncompressed]
 * @property {number} [_load_start]
 * @property {number} [_load_start_float]
 * @property {number} [_load_ms]
 * @property {number} [_load_end]
 * @property {number} [_ttfb_start]
 * @property {number} [_ttfb_end]
 * @property {number} [_ttfb_ms]
 * @property {number} [_download_start]
 * @property {number} [_download_end]
 * @property {number} [_download_ms]
 * @property {number} [_dns_start]
 * @property {number} [_dns_end]
 * @property {number} [_dns_ms]
 * @property {number} [_connect_start]
 * @property {number} [_connect_end]
 * @property {number} [_connect_ms]
 * @property {number} [_ssl_start]
 * @property {number} [_ssl_end]
 * @property {number} [_ssl_ms]
 * @property {number} [_all_start]
 * @property {number} [_all_end]
 * @property {number} [_all_ms]
 * @property {number} [_server_rtt]
 * @property {number} [_server_count]
 * @property {number} [_created]
 * @property {number} [_blockingTime]
 * @property {number} [_cpuTime]
 * @property {number} [_score_cache]
 * @property {number} [_score_cdn]
 * @property {number} [_score_gzip]
 * @property {number} [_score_cookies]
 * @property {number} [_score_keep-alive]
 * @property {number} [_score_minify]
 * @property {number} [_score_combine]
 * @property {number} [_score_compress]
 * @property {number} [_score_etags]
 * @property {number} [_gzip_total]
 * @property {number} [_gzip_save]
 * @property {number} [_minify_total]
 * @property {number} [_minify_save]
 * @property {number} [_image_total]
 * @property {number} [_image_save]
 * @property {number} [_cache_time]
 * @property {string|number} [_connectionId]
 * @property {string} [_fromCache]
 * @property {string} [_initiator_function]
 * @property {boolean} [_isLinkPreload]
 * @property {boolean} [_preloadUnused]
 * @property {boolean} [_renderBlocking]
 * @property {string} [_resourceType]
 * @property {string} [_securityState]
 * @property {string|number} [_server_port]
 * @property {string} [_socket_group]
 * @property {number} [_http2_stream_id]
 * @property {number} [_jpeg_scan_count]
 * @property {number} [_score_progressive_jpeg]
 */

/**
 * @typedef {Object} ExtendedHARResponse
 * @property {string} [_error]
 * @property {boolean} [_fetchedViaServiceWorker]
 * @property {number} [_transferSize]
 */

/**
 * @typedef {Object} ExtendedHARTimings
 * @property {number} [_blocked_queueing]
 * @property {number} [_workerFetchStart]
 * @property {number} [_workerReady]
 * @property {number} [_workerRespondWithSettled]
 * @property {number} [_workerStart]
 */

/**
 * @typedef {Object} ExtendedHARPage
 * @property {string} startedDateTime
 * @property {string} id
 * @property {string} title
 * @property {Object} pageTimings
 * 
 * -- Waterfall Tools Extended Page Dictionaries & Arrays --
 * @property {Object} [_requests]
 * @property {Object} [_cpuTimes]
 * @property {Object} [_cpuTimesDoc]
 * @property {Object} [_v8Stats]
 * @property {Object} [_audit_issues]
 * @property {Object} [_execution_contexts]
 * @property {Object} [_webdx_features]
 * @property {Object} [_viewport]
 * @property {Object} [_origin_dns]
 * @property {Object} [_detected]
 * @property {Object} [_detected_apps]
 * @property {Object} [_detected_technologies]
 * @property {Object} [_axe]
 * @property {Object} [_userTimes]
 * @property {Object} [_userTimingMeasures]
 * @property {Object} [_custom]
 * @property {Object} [_aurora]
 * @property {Object} [_cms]
 * @property {Object} [_cookies]
 * @property {Object} [_crawl_links]
 * @property {Object} [_ecommerce]
 * @property {Object} [_event-names]
 * @property {Object} [_fugu-apis]
 * @property {Object} [_generated-content]
 * @property {Object} [_initiators]
 * @property {Object} [_origin-trials]
 * @property {Object} [_parsed_css]
 * @property {Object} [_performance]
 * @property {Object} [_privacy-sandbox]
 * @property {Object} [_pwa]
 * @property {Object} [_robots_meta]
 * @property {Object} [_valid-head]
 * @property {Object} [_interactivePeriods]
 * @property {Object} [_longTasks]
 * @property {Object} [_largestPaints]
 * @property {Object} [_chromeUserTiming]
 * @property {Object} [_blinkFeatureFirstUsed]
 * @property {Object} [_utilization]
 * @property {Object} [_pages]
 * @property {Object} [_thumbnails]
 * @property {Object} [_images]
 * @property {Object} [_rawData]
 * @property {Object} [_videoFrames]
 * @property {Object} [_domains]
 * @property {Object} [_breakdown]
 * @property {Object} [_consoleLog]
 * @property {Object} [_wpt_bodies]
 * @property {Object} [_usertiming]
 * 
 * -- Waterfall Tools Extended Page Scalars --
 * @property {string} [_URL]
 * @property {string} [_document_URL]
 * @property {string} [_document_hostname]
 * @property {string} [_document_origin]
 * @property {string} [_final_url]
 * @property {string} [_testUrl]
 * @property {string} [_testID]
 * @property {string} [_browser_name]
 * @property {string} [_browser_version]
 * @property {string} [_osPlatform]
 * @property {string} [_osVersion]
 * @property {string} [_os_version]
 * @property {string} [_base_page_ip_ptr]
 * @property {string} [_base_page_cname]
 * @property {string} [_base_page_dns_server]
 * @property {string} [_LargestContentfulPaintType]
 * @property {string} [_LargestContentfulPaintNodeType]
 * @property {number} [_loadTime]
 * @property {number} [_docTime]
 * @property {number} [_fullyLoaded]
 * @property {number} [_bytesOut]
 * @property {number} [_bytesOutDoc]
 * @property {number} [_bytesIn]
 * @property {number} [_bytesInDoc]
 * @property {number} [_requestsFull]
 * @property {number} [_requestsDoc]
 * @property {number} [_responses_200]
 * @property {number} [_responses_404]
 * @property {number} [_responses_other]
 * @property {number} [_result]
 * @property {number} [_test_result]
 * @property {number} [_testStartOffset]
 * @property {number} [_test_run_time_ms]
 * @property {number} [_cached]
 * @property {number} [_optimization_checked]
 * @property {number} [_main_frame]
 * @property {number} [_run]
 * @property {number} [_step]
 * @property {number} [_start_epoch]
 * @property {number} [_date]
 * @property {number} [_connections]
 * @property {number} [_final_base_page_request]
 * @property {string} [_final_base_page_request_id]
 * @property {number} [_domElements]
 * @property {number} [_domTime]
 * @property {number} [_titleTime]
 * @property {number} [_server_rtt]
 * @property {number} [_effectiveBps]
 * @property {number} [_effectiveBpsDoc]
 * @property {number} [_TTFB]
 * @property {number} [_SpeedIndex]
 * @property {number} [_LastInteractive]
 * @property {number} [_TotalBlockingTime]
 * @property {number} [_maxFID]
 * @property {number} [_TTIMeasurementEnd]
 * @property {number} [_firstContentfulPaint]
 * @property {number} [_firstPaint]
 * @property {number} [_firstImagePaint]
 * @property {number} [_firstMeaningfulPaint]
 * @property {number} [_renderBlockingCSS]
 * @property {number} [_renderBlockingJS]
 * @property {number} [_loadEventStart]
 * @property {number} [_loadEventEnd]
 * @property {number} [_domContentLoadedEventStart]
 * @property {number} [_domContentLoadedEventEnd]
 * @property {number} [_domInteractive]
 * @property {number} [_domComplete]
 * @property {number} [_domLoading]
 * @property {number} [_lastVisualChange]
 * @property {number} [_render]
 * @property {number} [_visualComplete85]
 * @property {number} [_visualComplete90]
 * @property {number} [_visualComplete95]
 * @property {number} [_visualComplete99]
 * @property {number} [_visualComplete]
 */

/**
 * @typedef {Object} ExtendedHARLog
 * @property {string} version - Standard is "1.2"
 * @property {Creator} creator
 * @property {ExtendedHARPage[]} pages
 * @property {ExtendedHAREntry[]} entries
 */

/**
 * @typedef {Object} ExtendedHAR
 * @property {ExtendedHARLog} log
 */

export {};
